### ISSUE TITLE
Generate Coupon Code Error

### ISSUE THREAD

**Issue by gino2014** [landofcoder/module-coupon-generation#4]
Hello Support Team,

we generated a rule and after that by clicking to generate coupon code we are not able to generate them.

We got the following message:

Return value of Lof\CouponCode\Ui\Component\MassAction\Group\Options::jsonSerialize() must be an instance of Lof\CouponCode\Ui\Component\MassAction\Group\mixed, array returned

and 
Exception in /home/xxxx/yyyyyy.com/vendor/landofcoder/module-coupon-code/Ui/Component/MassAction/Group/Options.php:135

Kind Regards
Gino

**Comment by landofcoder** [comment]
Hi @gino2014 
Please try to setup the module version 1.0.8 https://github.com/landofcoder/module-coupon-generation/releases/tag/1.0.8

We fixed issue in version 1.0.8
